"""Add comments table

Revision ID: 014c388fb8fe
Revises: 9aedd9c56c28
Create Date: 2026-06-24 15:53:11.871782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014c388fb8fe'
down_revision: Union[str, Sequence[str], None] = '9aedd9c56c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_index(op.f('ix_calificacion_id_comentario'), 'calificacion', ['id_comentario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calificacion_id_comentario'), table_name='calificacion')
    op.drop_table('calificacion')
    # ### end Alembic commands ###
