"""Add EN_TALLER and numero_orden

Revision ID: 2057ebe163b3
Revises: 24efa7936266
Create Date: 2026-07-01 20:21:05.400047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2057ebe163b3'
down_revision: Union[str, Sequence[str], None] = '24efa7936266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes_servicio', sa.Column('numero_orden', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_ordenes_servicio_numero_orden'), 'ordenes_servicio', ['numero_orden'], unique=True)
    
    # We set existing rows to a default before making it nullable=False
    op.execute("UPDATE ordenes_servicio SET numero_orden = 'ORD-' || id_orden::text WHERE numero_orden IS NULL")
    op.alter_column('ordenes_servicio', 'numero_orden', nullable=False)

    # Alter Enum ConfirmationState
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE confirmationstate ADD VALUE IF NOT EXISTS 'EN_TALLER'")
        op.execute("ALTER TYPE confirmationstate ADD VALUE IF NOT EXISTS 'CANCELADO_POR_SISTEMA'")
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordenes_servicio_numero_orden'), table_name='ordenes_servicio')
    op.drop_column('ordenes_servicio', 'numero_orden')
    # ### end Alembic commands ###
