"""Add motivo_rechazo to bookings

Revision ID: 24efa7936266
Revises: c05e9b08ffd6
Create Date: 2026-07-01 18:57:47.537482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24efa7936266'
down_revision: Union[str, Sequence[str], None] = 'c05e9b08ffd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamientos', sa.Column('motivo_rechazo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendamientos', 'motivo_rechazo')
    # ### end Alembic commands ###
