"""Crear tabla vehiculos

Revision ID: 32e3f78521dc
Revises: 0c3e4bfec771
Create Date: 2026-06-11 20:37:48.329240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e3f78521dc'
down_revision: Union[str, Sequence[str], None] = '0c3e4bfec771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(length=50), nullable=False),
    sa.Column('kilometraje_actual', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_vehiculo')
    )
    op.create_index(op.f('ix_vehicles_id_vehiculo'), 'vehicles', ['id_vehiculo'], unique=False)
    op.create_index(op.f('ix_vehicles_placa'), 'vehicles', ['placa'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_placa'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id_vehiculo'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
