"""Refactor vehiculos: renombrar tabla, eliminar kilometraje y agregar enum

Revision ID: 3589a886172f
Revises: 32e3f78521dc
Create Date: 2026-06-12 19:34:17.217410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3589a886172f'
down_revision: Union[str, Sequence[str], None] = '32e3f78521dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('tipo_vehiculo', sa.Enum('camion', 'volqueta', 'patineta', 'mula', 'bus', 'otro', name='tipovehiculoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id_vehiculo')
    )
    op.create_index(op.f('ix_vehiculos_id_vehiculo'), 'vehiculos', ['id_vehiculo'], unique=False)
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_id_vehiculo'), table_name='vehiculos')
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
