"""Initial schema

Revision ID: 5a0bfee53257
Revises: 
Create Date: 2026-07-23 15:58:48.884135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0bfee53257'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup_audit_logs',
    sa.Column('id_cleanup_audit', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id_cleanup_audit')
    )
    op.create_index('ix_cleanup_audit_job_created_at', 'cleanup_audit_logs', ['job_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_cleanup_audit_logs_entity_name'), 'cleanup_audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_cleanup_audit_logs_id_cleanup_audit'), 'cleanup_audit_logs', ['id_cleanup_audit'], unique=False)
    op.create_index(op.f('ix_cleanup_audit_logs_job_name'), 'cleanup_audit_logs', ['job_name'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('rol', sa.Enum('admin', 'mechanic', 'secretary', 'client', name='userrole', native_enum=False), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_cedula'), 'usuarios', ['cedula'], unique=True)
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_usuarios_verification_token'), 'usuarios', ['verification_token'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('tipo_vehiculo', sa.Enum('camion', 'volqueta', 'patineta', 'mula', 'bus', 'otro', name='tipovehiculoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id_vehiculo')
    )
    op.create_index(op.f('ix_vehiculos_id_vehiculo'), 'vehiculos', ['id_vehiculo'], unique=False)
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.create_table('agendamientos',
    sa.Column('id_agendamiento', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('fecha_cita', sa.Date(), nullable=False),
    sa.Column('hora_cita', sa.Time(), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('estado_confirmacion', sa.Enum('PENDIENTE', 'CONFIRMADO', 'RECHAZADO', 'CANCELADO', 'EN_TALLER', 'CANCELADO_POR_SISTEMA', name='confirmationstate'), nullable=False),
    sa.Column('motivo_rechazo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_agendamiento')
    )
    op.create_index(op.f('ix_agendamientos_id_agendamiento'), 'agendamientos', ['id_agendamiento'], unique=False)
    op.create_table('calificacion',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_index(op.f('ix_calificacion_id_comentario'), 'calificacion', ['id_comentario'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token', name='uq_device_tokens_fcm_token'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_device_tokens_user_device')
    )
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index('ix_device_tokens_user_active', 'device_tokens', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('invitacion_vehiculo',
    sa.Column('id_invitacion', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_usuario_creador', sa.Integer(), nullable=False),
    sa.Column('codigo_secreto', sa.String(length=6), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('fue_usada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_creador'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_invitacion')
    )
    op.create_index(op.f('ix_invitacion_vehiculo_codigo_secreto'), 'invitacion_vehiculo', ['codigo_secreto'], unique=True)
    op.create_index(op.f('ix_invitacion_vehiculo_id_invitacion'), 'invitacion_vehiculo', ['id_invitacion'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index('ix_messages_sender_receiver', 'messages', ['sender_id', 'receiver_id'], unique=False)
    op.create_index('ix_messages_timestamp', 'messages', ['timestamp'], unique=False)
    op.create_table('vehiculos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('rol_vehiculo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_usuarios_id'), 'vehiculos_usuarios', ['id'], unique=False)
    op.create_table('ordenes_servicio',
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('numero_orden', sa.String(length=20), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_mecanico', sa.Integer(), nullable=True),
    sa.Column('id_agendamiento', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('hora_ingreso', sa.Time(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=False),
    sa.Column('cliente_identificacion', sa.String(length=50), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=20), nullable=False),
    sa.Column('conductor_nombre', sa.String(length=100), nullable=True),
    sa.Column('conductor_telefono', sa.String(length=20), nullable=True),
    sa.Column('kilometraje_ingreso', sa.Integer(), nullable=False),
    sa.Column('nivel_combustible', sa.String(length=50), nullable=False),
    sa.Column('trabajos_a_realizar', sa.Text(), nullable=False),
    sa.Column('informe_trabajo', sa.Text(), nullable=True),
    sa.Column('estado_orden', sa.Enum('EN_DIAGNOSTICO', 'EN_REPARACION', 'LISTO_PARA_ENTREGA', 'ENTREGADO', name='serviceorderstate'), nullable=False),
    sa.ForeignKeyConstraint(['id_agendamiento'], ['agendamientos.id_agendamiento'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_mecanico'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_index(op.f('ix_ordenes_servicio_id_orden'), 'ordenes_servicio', ['id_orden'], unique=False)
    op.create_index(op.f('ix_ordenes_servicio_numero_orden'), 'ordenes_servicio', ['numero_orden'], unique=True)
    op.create_table('informes_tecnicos',
    sa.Column('id_informe_tecnico', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('diagnostico', sa.String(length=500), nullable=False),
    sa.Column('recomendaciones', sa.String(length=1500), nullable=True),
    sa.Column('repuestos_usados', sa.String(length=1000), nullable=True),
    sa.Column('imagenes_repuestos', sa.String(length=2000), nullable=True),
    sa.Column('estado_revision', sa.String(length=50), nullable=False),
    sa.Column('observaciones_admin', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes_servicio.id_orden'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_informe_tecnico')
    )
    op.create_index(op.f('ix_informes_tecnicos_id_informe_tecnico'), 'informes_tecnicos', ['id_informe_tecnico'], unique=False)
    op.create_table('recibos',
    sa.Column('id_recibo', sa.Integer(), nullable=False),
    sa.Column('numero_recibo', sa.String(length=20), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=False),
    sa.Column('cliente_nit', sa.String(length=50), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=20), nullable=True),
    sa.Column('cliente_direccion', sa.String(length=150), nullable=True),
    sa.Column('cliente_ciudad', sa.String(length=100), nullable=True),
    sa.Column('cliente_correo', sa.String(length=150), nullable=True),
    sa.Column('vendedor', sa.String(length=100), nullable=True),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('forma_pago', sa.String(length=50), nullable=True),
    sa.Column('concepto', sa.String(length=200), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('iva_total', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('valor_en_letras', sa.String(length=255), nullable=True),
    sa.Column('nota_pie', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes_servicio.id_orden'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_recibo')
    )
    op.create_index(op.f('ix_recibos_id_recibo'), 'recibos', ['id_recibo'], unique=False)
    op.create_index(op.f('ix_recibos_numero_recibo'), 'recibos', ['numero_recibo'], unique=True)
    op.create_table('detalles_recibo',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_recibo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('porcentaje_iva', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_recibo'], ['recibos.id_recibo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalles_recibo_id_detalle'), 'detalles_recibo', ['id_detalle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_recibo_id_detalle'), table_name='detalles_recibo')
    op.drop_table('detalles_recibo')
    op.drop_index(op.f('ix_recibos_numero_recibo'), table_name='recibos')
    op.drop_index(op.f('ix_recibos_id_recibo'), table_name='recibos')
    op.drop_table('recibos')
    op.drop_index(op.f('ix_informes_tecnicos_id_informe_tecnico'), table_name='informes_tecnicos')
    op.drop_table('informes_tecnicos')
    op.drop_index(op.f('ix_ordenes_servicio_numero_orden'), table_name='ordenes_servicio')
    op.drop_index(op.f('ix_ordenes_servicio_id_orden'), table_name='ordenes_servicio')
    op.drop_table('ordenes_servicio')
    op.drop_index(op.f('ix_vehiculos_usuarios_id'), table_name='vehiculos_usuarios')
    op.drop_table('vehiculos_usuarios')
    op.drop_index('ix_messages_timestamp', table_name='messages')
    op.drop_index('ix_messages_sender_receiver', table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_invitacion_vehiculo_id_invitacion'), table_name='invitacion_vehiculo')
    op.drop_index(op.f('ix_invitacion_vehiculo_codigo_secreto'), table_name='invitacion_vehiculo')
    op.drop_table('invitacion_vehiculo')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index('ix_device_tokens_user_active', table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_calificacion_id_comentario'), table_name='calificacion')
    op.drop_table('calificacion')
    op.drop_index(op.f('ix_agendamientos_id_agendamiento'), table_name='agendamientos')
    op.drop_table('agendamientos')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_id_vehiculo'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_usuarios_verification_token'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cedula'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_cleanup_audit_logs_job_name'), table_name='cleanup_audit_logs')
    op.drop_index(op.f('ix_cleanup_audit_logs_id_cleanup_audit'), table_name='cleanup_audit_logs')
    op.drop_index(op.f('ix_cleanup_audit_logs_entity_name'), table_name='cleanup_audit_logs')
    op.drop_index('ix_cleanup_audit_job_created_at', table_name='cleanup_audit_logs')
    op.drop_table('cleanup_audit_logs')
    # ### end Alembic commands ###
