"""increase_user_role_length

Revision ID: 8527a52f83a1
Revises: 1ed5acfe4691
Create Date: 2026-07-15 18:17:08.140111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8527a52f83a1'
down_revision: Union[str, Sequence[str], None] = '1ed5acfe4691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('admin', 'mechanic', 'secretary', 'client', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'rol',
               existing_type=sa.Enum('admin', 'mechanic', 'secretary', 'client', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
