"""Add missing receipt fields

Revision ID: 970e7d2cb57e
Revises: 8527a52f83a1
Create Date: 2026-07-16 20:53:06.543490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970e7d2cb57e'
down_revision: Union[str, Sequence[str], None] = '8527a52f83a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'agendamientos', 'usuarios', ['id_usuario'], ['id_usuario'])
    op.add_column('recibos', sa.Column('numero_recibo', sa.String(length=20), nullable=False))
    op.add_column('recibos', sa.Column('tipo_documento', sa.String(length=50), nullable=False))
    op.add_column('recibos', sa.Column('estado', sa.String(length=50), nullable=False))
    op.add_column('recibos', sa.Column('cliente_telefono', sa.String(length=20), nullable=True))
    op.alter_column('recibos', 'id_orden',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('recibos_id_orden_key'), 'recibos', type_='unique')
    op.create_index(op.f('ix_recibos_numero_recibo'), 'recibos', ['numero_recibo'], unique=True)
    op.drop_constraint(op.f('recibos_id_orden_fkey'), 'recibos', type_='foreignkey')
    op.create_foreign_key(None, 'recibos', 'ordenes_servicio', ['id_orden'], ['id_orden'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recibos', type_='foreignkey')
    op.create_foreign_key(op.f('recibos_id_orden_fkey'), 'recibos', 'ordenes_servicio', ['id_orden'], ['id_orden'], ondelete='CASCADE')
    op.drop_index(op.f('ix_recibos_numero_recibo'), table_name='recibos')
    op.create_unique_constraint(op.f('recibos_id_orden_key'), 'recibos', ['id_orden'], postgresql_nulls_not_distinct=False)
    op.alter_column('recibos', 'id_orden',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recibos', 'cliente_telefono')
    op.drop_column('recibos', 'estado')
    op.drop_column('recibos', 'tipo_documento')
    op.drop_column('recibos', 'numero_recibo')
    op.drop_constraint(None, 'agendamientos', type_='foreignkey')
    # ### end Alembic commands ###
