"""Add TechnicalReport

Revision ID: 9aedd9c56c28
Revises: d177e83dd324
Create Date: 2026-06-16 17:24:12.463507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aedd9c56c28'
down_revision: Union[str, Sequence[str], None] = 'd177e83dd324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informes_tecnicos',
    sa.Column('id_informe_tecnico', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('diagnostico', sa.String(length=500), nullable=False),
    sa.Column('recomendaciones', sa.String(length=1500), nullable=True),
    sa.Column('repuestos_usados', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes_servicio.id_orden'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_informe_tecnico')
    )
    op.create_index(op.f('ix_informes_tecnicos_id_informe_tecnico'), 'informes_tecnicos', ['id_informe_tecnico'], unique=False)
    op.drop_index(op.f('ix_vehicles_id_vehiculo'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_placa'), table_name='vehicles')
    op.drop_table('vehicles')
    op.alter_column('usuarios', 'cedula',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('vehiculos', 'kilometraje_actual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('kilometraje_actual', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('usuarios', 'cedula',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('vehicles',
    sa.Column('id_vehiculo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('marca', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tipo_vehiculo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('kilometraje_actual', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_vehiculo', name=op.f('vehicles_pkey'))
    )
    op.create_index(op.f('ix_vehicles_placa'), 'vehicles', ['placa'], unique=True)
    op.create_index(op.f('ix_vehicles_id_vehiculo'), 'vehicles', ['id_vehiculo'], unique=False)
    op.drop_index(op.f('ix_informes_tecnicos_id_informe_tecnico'), table_name='informes_tecnicos')
    op.drop_table('informes_tecnicos')
    # ### end Alembic commands ###
