"""Add receipt tables and admin review fields

Revision ID: c05e9b08ffd6
Revises: f7831daad685
Create Date: 2026-07-01 17:28:12.161967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05e9b08ffd6'
down_revision: Union[str, Sequence[str], None] = 'f7831daad685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recibos',
    sa.Column('id_recibo', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=False),
    sa.Column('cliente_nit', sa.String(length=50), nullable=False),
    sa.Column('cliente_direccion', sa.String(length=150), nullable=True),
    sa.Column('cliente_ciudad', sa.String(length=100), nullable=True),
    sa.Column('vendedor', sa.String(length=100), nullable=True),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('forma_pago', sa.String(length=50), nullable=True),
    sa.Column('concepto', sa.String(length=200), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('iva_total', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('valor_en_letras', sa.String(length=255), nullable=True),
    sa.Column('nota_pie', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes_servicio.id_orden'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_recibo'),
    sa.UniqueConstraint('id_orden')
    )
    op.create_index(op.f('ix_recibos_id_recibo'), 'recibos', ['id_recibo'], unique=False)
    op.create_table('detalles_recibo',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_recibo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('porcentaje_iva', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_recibo'], ['recibos.id_recibo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalles_recibo_id_detalle'), 'detalles_recibo', ['id_detalle'], unique=False)
    op.add_column('informes_tecnicos', sa.Column('estado_revision', sa.String(length=50), nullable=False))
    op.add_column('informes_tecnicos', sa.Column('observaciones_admin', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informes_tecnicos', 'observaciones_admin')
    op.drop_column('informes_tecnicos', 'estado_revision')
    op.drop_index(op.f('ix_detalles_recibo_id_detalle'), table_name='detalles_recibo')
    op.drop_table('detalles_recibo')
    op.drop_index(op.f('ix_recibos_id_recibo'), table_name='recibos')
    op.drop_table('recibos')
    # ### end Alembic commands ###
