"""Add vehicle users and invitations

Revision ID: e7a72e33e80e
Revises: f3b3f989589a
Create Date: 2026-06-13 11:42:34.822124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a72e33e80e'
down_revision: Union[str, Sequence[str], None] = 'f3b3f989589a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitacion_vehiculo',
    sa.Column('id_invitacion', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_usuario_creador', sa.Integer(), nullable=False),
    sa.Column('codigo_secreto', sa.String(length=6), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('fue_usada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_creador'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_invitacion')
    )
    op.create_index(op.f('ix_invitacion_vehiculo_codigo_secreto'), 'invitacion_vehiculo', ['codigo_secreto'], unique=True)
    op.create_index(op.f('ix_invitacion_vehiculo_id_invitacion'), 'invitacion_vehiculo', ['id_invitacion'], unique=False)
    op.create_table('vehiculos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('rol_vehiculo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_usuarios_id'), 'vehiculos_usuarios', ['id'], unique=False)
    
    # PROTECCIÓN CONTRA BORRADOS FANTASMAS:
    op.drop_index(op.f('ix_vehicles_id_vehiculo'), table_name='vehicles', if_exists=True)
    op.drop_index(op.f('ix_vehicles_placa'), table_name='vehicles', if_exists=True)
    # op.drop_table('vehicles') # <-- COMENTADO PORQUE LA TABLA NO EXISTE LOCALMENTE
    
    op.execute("UPDATE usuarios SET cedula = 'TMP_' || id_usuario::text WHERE cedula IS NULL")
    op.alter_column('usuarios', 'cedula',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'cedula',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('vehicles',
    sa.Column('id_vehiculo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('marca', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tipo_vehiculo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('kilometraje_actual', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_vehiculo', name=op.f('vehicles_pkey'))
    )
    op.create_index(op.f('ix_vehicles_placa'), 'vehicles', ['placa'], unique=True)
    op.create_index(op.f('ix_vehicles_id_vehiculo'), 'vehicles', ['id_vehiculo'], unique=False)
    op.drop_index(op.f('ix_vehiculos_usuarios_id'), table_name='vehiculos_usuarios')
    op.drop_table('vehiculos_usuarios')
    op.drop_index(op.f('ix_invitacion_vehiculo_id_invitacion'), table_name='invitacion_vehiculo')
    op.drop_index(op.f('ix_invitacion_vehiculo_codigo_secreto'), table_name='invitacion_vehiculo')
    op.drop_table('invitacion_vehiculo')
    # ### end Alembic commands ###